default: &default
  type: server_db
  url: http://neo4j:password@localhost:7474

noauth:
  type: server_db
  url: http://localhost:7474

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default